# Generated by Django 6.0.2 on 2026-02-10 09:07

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('RUB', 'Ruble'), ('USD', 'US Dollar'), ('EUR', 'Euro')], max_length=3)),
                ('recipient_details', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='new', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payout',
                'verbose_name_plural': 'Payouts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payouts_pay_status_a5ad2e_idx'), models.Index(fields=['-created_at'], name='payouts_pay_created_182fdd_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payout_amount_gt_zero')],
            },
        ),
    ]
